from django.urls import include, path
from rest_framework.routers import DefaultRouter

# Importing all views (DepartmentViewSets, EmployeelistCreateViews, EmployeListeDetailsView)
from employees.views import *

# =====================================================================
# ROUTER SETUP
# =====================================================================
# Create a router object from the DefaultRouter class.
# This will automatically generate the standard URL patterns for our ViewSets.
router = DefaultRouter()

# Register the Department ViewSet.
# This single registration automatically builds:
# - GET /department/      (List)
# - POST /department/     (Create)
# - GET /department/{id}/ (Detail)
# ... and so on.
router.register('department', DepartmentViewSets, basename='department')


# =====================================================================
# URL PATTERNS
# =====================================================================
urlpatterns = [
    # 👥 EMPLOYEE ENDPOINTS (Manually mapped using Class-Based Generic Views)
    
    # Collection Endpoint: Handles listing all employees and creating new ones.
    # .as_view() converts the Django Rest Framework class into a usable Django view.
    path('employees/', EmployeelistCreateViews.as_view(), name='employee-list-create'),
    
    # Instance Endpoint: Handles fetching, updating, or deleting an individual employee.
    # '<int:pk>' captures the ID number from the URL and passes it to the view as the Primary Key.
    path('employees/<int:pk>/', EmployeListeDetailsView.as_view(), name='employee-detail'),


    # 🏢 DEPARTMENT ENDPOINTS (Automatically mapped using the Router)
    
    # Include all the URLs generated by our DefaultRouter.
    # Leaving the prefix path empty ('') means these endpoints mount right at the root.
    path('', include(router.urls)),
]